### ISSUE TITLE
Problem with sshnuke :-)

### ISSUE THREAD

**Issue by stullii** [neon-ninja/scripts#1]
I am not very familiar with shell scripts, but I think line 13:
`pw=${pw#"--rootpw="}
`is supposed to cut "-rootpw" off $pw.
But it doesnt, so I'm getting:
`resetting root password to "-rootpw=Z10N0101"
`instead of:
`resetting root password to "Z10N0101"
` running on Debian 9.4 with bash.

**Comment by neon-ninja** [comment]
it expects two dashes, like:

--rootpw

not

-rootpw

**Comment by neon-ninja** [comment]
though taking a look at https://www.youtube.com/watch?v=0PxTAn4g20U it looks like trinity uses a single dash for her arguments

**Comment by neon-ninja** [comment]
https://github.com/neon-ninja/scripts/commit/3afd7fbbe6b22301e739006539605372425f417e should fix this, give it a try
